language: node_js
node_js:
- '8'
before_install:
- stty cols 120
- export COLUMNS=120
script:
- yarn run manifest:firefox
- yarn run lint:eslint
- yarn run lint:addons
deploy:
  provider: script
  script: yarn install --dev && cd src && jq -s add manifest.json.default manifest.json.chrome > manifest.json && yarn run webstore upload --auto-publish --extension-id=okmlpjijminjkikninbkcnfmhkofgnnk
  on:
    branch: master
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: NX7Aa/44LWzNqEbK8kTCa6tkNpQCc1GYv9k31WsJd7k4fhy+6w+vCzf1t5lx5zxm8406n1IZVzP+FfxZXDBI+t9F3DkJ4cQQN4bpaQ8brn4A2DSpDsrrttXbHUF0QRgME45eK5fcJALryLsS9CdHerQI91Jt69crD6ELzgQi7YMRfa5Bj5S2wKg8G8dgAobmJKY/UtKMDEMYjddQL980c9yCqzbzQgVcTMrEXvDj4OJGHECJxkr0Rnyg26Jt1MPAChPIHeTEySB/ZzyZ4/ibyfpfCCDdhRFulfPYgnujKkQzeqeFTARGfZ+gXaXzMTOs1LvDW2PPqjEolCX0EG6gMz53WB+58c75krtS9Hs/QmX3MHGaKZVkYWbp5Ga7I8ydRFEXsC+LUK++qR1nhR7QZ8+O7cPJ5IIqspVZ8+bh2EjLD+fsV4tmbsdjKHnYPMLzuIWQ+wEYyczO0sjvpIWGJzlVRZVVTa39j6hsy/ALvm6SU9YvAoWsd9gbouGunp/yJZyFRMSPjmSMsya0QFJULoQ07+wSLzQZ+g/Fu9Om5bKGRDs/Edog3cyHEFIWsV9mWDDLzPNbrAEltQk+LBVPWX0Rq6hJswGVUbdTFHwghY/mOkpXQr8uY3jQpj4ND/3gCWskltEmTMDheDxxY2GKQIgewWqeAycyxfN21aNUIcg=
  - secure: GHVsBRRp4JRJKsL+JF1JUGfIzQBolA09Vjt4+a05PRp1MHG6jkZbXn7XjCDESVh+1MRBQLrFqA2NKdg7eujlEJ9njLRneBceeE9D2I97WC8Io0CKy7PL0COdnSUzjKpIcynAZidZvX9a3SzDVUPo75VvUOcEFcQGMiiqQ0KBwTLtMCz353MC/Y6jGLS2bbm6f6VcO3cTn2aHZl6oR1AbUT/mh7SHXMPHaXp5CG/XZYZg8lY5Z3lDrE18j5b6ngCZ7ALJabNoyEaooW7Bo+L/E6voHg6D7zsG6wWZwmdkjFRjHm4aZS53F/GP4m4EWONxfNfL029pl3MAz8ExgvQ61Rxbyr0NC7mdURipvHn9H29YxIVP4dk2piurDPA3lweS4aENXHNBMDp09hpYpi2EmJlqLENaYinRr7SZYecYqw2UsgV/YwQaUahQ9kuDVW5rQ9BrUW990L2FZE/RtNsjFCunJ+fMNS2Pi8LTtSgAUlYwq+biUfnEwdcUXWHBXh73IMrl+F/k1RyCqAx7Ti18TGwDxzkRBPJbbUXFzCN3Q5K2Scgujh4iYx9I71/L5RVGfGCVU/S7/r9E5A6q65559jFZvANx3m5+2aCqgeToHR8b4ciPLYSy3IsAs8uChVr9fj8NQdWG8U7wXznMQ8tMOchUKaMKCi2PVFObxzUuJSs=
  - secure: J0yAiR9NasulXm6RPxWdjNvTHXc18lmftrPu3FJXJUWTYDWinsrFF672QQeWdCPiarJb9U000ykePgkCT5HDa3OgcoONqCzDQnByZcRuxCylBK2nuWmTiLiQs+N+Q5qLuBU3aCSPJey6OVpImGy5ovJI10bZ789YVfyYEJpvMRUNYF+hkmUYo1ONPQYDjoMR914k0hIFaZFLNavXuKJFcXWM1uGJ5i7iT3Kqt1BelW+t/9WtBkTx7QiZo/aGcm6RouQ0uqQCaZY88JjEuVlM7UmCC9/EI+WtAbjlBTsxqLb788M2EHXFeARQPNaOVHTJu5UcKrzPuM8D2Gs4f7IveSsuO/xAX8jKLywNUJWnXLLXSr91fEymMZLsIBXFsVD8/PqB0w+DMMgDdaZAHPEdvwm4iX0cst3Jr7RpPEYWs2jQwApeuPWTLVswBac19RE0gJLsvXif55/VxWZ5rBK51gF7369/JiBFaLq6ehCh6rS/5+gJewPgO7mwSoFy52gkKF0pb2MaaTqcQwOlagq0fTASPoFZcG33vNoexusR5c4gxfDqt5vfrxMKqaGGPm9vnOD4hLIhnQRnLgbGp/xF+IO1FtCOv6zRFFRuHhr/jUr7uzsHb5a2Uh/RUPtWeZ4ajz2owaNkb4Ph6MocTEiY+6iaCli2yKadGUxJJPWnZzo=
